name: usegalaxy.* installation

on:
  schedule:
    # Run at midnight every Thursday
    - cron: '0 0 * * 4'
  push:
    branches: [ main ]

jobs:
  workflow-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: py-cache
      - name: Run a multi-line script
        run: |
          pip install bioblend
          python scripts/usegalaxy_star_upload.py
